### PR TITLE
Remove nss 3.26 and use other missing packages (nss, nspr and etc)

### PR DESCRIPTION
**Pull request by msisov**
TBR=tonikitoo

### CODE REVIEW

**Comment by LiPengKun** [comment]
following step of this wiki, I'm using this meta-browser to build chromium image in AGL environment. But can not build successfully. and PC(16G RAM) was freezed. 
Can you build chromium successfully?

**Comment by msisov** [comment]
Yes, we can. What agl branch do you use? Does it just freeze? Can you try a fresh checkout of agl source code?

**Comment by LiPengKun** [comment]
My AGL version is MasterBranch. when compile chromium source code, the issue happened and PC is just freeze. As my research, I found that there are below failed action. I am not sure what happened. Can you give me some advice?
 

> **1.**[4252/26720] python ../../third_party/WebKit/Source/bindings/scripts/idl_compiler.py --cache-dir gen/blink/bindings/scripts --output-dir gen/blink/bindings/modules/v8 --info-dir gen/blink/bindings --target-component modules ../../third_party/WebKit/Source/modules/background_fetch/BackgroundFetchFailEventInit.idl

> **2.**  [4433/26720] python ../../third_party/WebKit/Source/bindings/scripts/idl_compiler.py --cache-dir gen/blink/bindings/scripts --output-dir gen/blink/bindings/modules/v8 --info-dir gen/blink/bindings --target-component modules ../../third_party/WebKit/Source/modules/background_fetch/BackgroundFetchFailEvent.idl

> **3.** [15634/26720]  aarch64-agl-linux-g++  -march=armv8-a --sysroot=/home/agl/M3Masterbranch/build/tmp/work/aarch64-agl-linux/chromium/20170928.r499098.git8eb8619a-dev0/recipe-sysroot  ...............................-o obj/net/net/failing_http_transaction_factory.o

>**4.**gen/third_party/WebKit/Source/core/animation/../../../../../../../../third_party/WebKit/Source/core/animation/CompositorAnimations.cpp: In static member function 'static blink::CompositorAnimations::FailureCode

**Review by tonikitoo — COMMENTED** [review]
lgtm.

It seems we were able to remove all custom nss patches, and switch to nss-native. Nice!

**Comment by LiPengKun** [comment]
I have resolve this problem. As my environment, I found it's need at least RAM 20GB to build chromium. through add swap file, this can be resolve. Thank you for your help.

**Pull request merged**
